### ISSUE TITLE
Multiroom

### ISSUE THREAD

**Issue by xipmix** [volumio/docs#55]
How is the 'multiroom' feature supposed to work exactly?
The _First Steps with Volumio_ chapter shows that if have multiple devices, they are shown in the UI and you can connect to each of them by cicking on them. But is the intention that:
 * one device controls what all the others play, or
 * each device may play a different track and the multiroom feature merely lets you see what is being played by any other device?

To me, the term 'multiroom' suggests the first option, that as you move from one room to another you can continue to listen to a piece of music, with all the subtle considerations about playback syncing being magically handled.

**Comment by volumio** [comment]
It's the second one. 
But (spoiler) we are working on synced multiroom playback.

**Comment by xipmix** [comment]
Ok thanks, I am about to make a PR mentioning this so good to know.
