### ISSUE TITLE
Update of npm modules and debian version?

### ISSUE THREAD

**Issue by synoniem** [volumio/docs#91]
Looking at Node's version number 10 (old!) used for Volumio2UI I am using a Docker container to build the UI. Even then I see a lot of deprecated notices and security warnings. Is anyone working at keeping this repo up to date or is this abandonware?  BTW building the UI depends on a X86/AMD64 only part maybe this should be mentioned in the build instructions?

The same for the Debian version (Jessie) that one is really old and archived at the time. Any updates to a higher version in the pipeline?

**Comment by xipmix** [comment]
There is lots of work going on to make a buster version. The forums have a beta test thread https://community.volumio.org/t/volumio-3-buster-beta-for-rpi/45263/279
Could you close this, the update of node etc is happening AIUI.
